# Site
name: 'NSShop'
title: 'NSShop - Прошивка(чіповка, чіпування) Nintendo Switch OLED Lite V2 та продаж готових варіантів'
description: 'Прошивка(чіповка, чіпування) Nintendo Switch всіх ревізій(встановлення і налаштування кастомної прошивки
для запуску ігор безкоштовно) та продаж вже готових варіантів як нових, так і вживаних.
Працюємо по всій Україні через Нову Пошту. Пишіть, телефонуйте - надаємо будь-які консультації, відповідаємо
на будь-які запитання. Також можете писати в телеграм або Viber. Телефон: +380960229701'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
google_analytics: 'G-6HZHLH7RWT'
disqus: ''
mailchimp-list: ''
include: [ '_pages' ]
permalink: /:title/

# SEO Tags
seo:
  name: 'NSShop'
  title: 'NSShop - Прошивка(чіповка, чіпування) Nintendo Switch OLED Lite V2 та продаж готових варіантів'
  tagline: 'Прошивка(чіповка, чіпування) та продаж готових варіантів для Nintendo Switch OLED Lite V2'
  description: 'Прошивка(чіповка, чіпування) Nintendo Switch всіх ревізій(встановлення і налаштування кастомної прошивки
для запуску ігор безкоштовно) та продаж вже готових варіантів як нових, так і вживаних.
Працюємо по всій Україні через Нову Пошту. Пишіть, телефонуйте - надаємо будь-які консультації, відповідаємо
на будь-які запитання. Також можете писати в телеграм або Viber. Телефон: +380960229701'
  url: 'https://nsshop.com.ua/'
  image: 'assets/images/logo.png'

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to 'enabled' to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: 'disabled'
adsense-data-ad-client: 'ca-pub-3412143450191416'
adsense-data-ad-slot: '1363087678'

# Lazy Images ('enabled' or 'disabled')
lazyimages: 'disabled'

exclude: [ changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock ]
